### ISSUE TITLE
dt2vw() changing by reference the input dataset

### ISSUE THREAD

**Issue by selimrbd** [eddelbuettel/rvw#3]
In the current implementation `dt2vw` creates side effects on the input data, as changes are made by reference.

E.g: 
```{r}
dt <- data.table::data.table(mtcars)
names(dt)
data.table::setnames(x = dt, old = "drat", new = "d'rat")
dt2vw(data = dt, fileName = "test.vw", target = "mpg")
```
Here, "d'rat" gets converted to "d_rat" by dt2vw as `'`is a special character to escape in variable names. The original 'dt' dataset also gets its variable name changed which I believe is not desirable.

**Comment by eddelbuettel** [comment]
So ... start with a `data.table::copy()` ?  

But aren't those objects transient?

**Comment by selimrbd** [comment]
Yes `data.table::copy()` would be enough but it would be nice also to avoid the memory overhead.

The user could be doing stuff in R too with the same input dataset (data exploration, running other algorithms...). So the side effect could mess things up silently.
