### ISSUE TITLE
dt2vw() - malformed example for numeric variables with missing values

### ISSUE THREAD

**Issue by selimrbd** [eddelbuettel/rvw#4]
dt2vw() parses incorrectly numeric variables containing NAs. Example:

```{r}
df <- data.frame(v1 = c(1,2,NA,4), v2 = letters[1:4], target = c(0,0,1,1))
rvw::dt2vw(data = df, fileName = "num_NA.vw", target = "target")
```
Running this file with vw yields:
`malformed example! Float expected after : "|A v1:"in Example #2: "|A v1:NA v2_c"`

Solution 1: for numeric variables, replace missing values by 0 (which are equivalent for vw), throwing a warning
Solution 2: throw an error and let the user figure out how he wants to handle his NAs

**Comment by eddelbuettel** [comment]
Hm.   I feel 2. is a bit more in the general spirit of R.  There are method which cannot deal with `NA`, so we omit, or impute, or ...   Just (somewhat silently) converting strikes me as less good.

**Comment by eddelbuettel** [comment]
@SelimRaboudi Can you check the branch I just pushed?  I has (very simple) fixes for #3 and #4.

**Comment by selimrbd** [comment]
@eddelbuettel yes validated I think we can close them

**Comment by eddelbuettel** [comment]
Great, thanks. 

By the way: I added a convenient command in the commit log for these two.  So if and when they get merged to master, the issue would get closed.  But thanks for closing them by hand.

And one more by the way:  interest and time to come back to this?  

I don't mean to monopolize rvw, I think we can 
- make this joint as a continuation of your initial r.vw, 
- get it ready for CRAN (it basically should be) 
- and then focus on the rewriting of [RVowpalWabbit](https://github.com/eddelbuettel/rvowpalwabbit) using the external libvw.  

What do you think?

**Comment by selimrbd** [comment]
Oh ok, got it :)

Yes I currently have a bit more time, work a lot on R and am interested in improving the interface with vw.

Yes, totally agree with your suggestions. Sounds like a plan !

Regarding RVowpalWabbit, I rewrote dt2vw() last year using Rcpp: https://github.com/SelimRaboudi/Rvwabbit/blob/master/R/dt2vw.R#L230
https://github.com/SelimRaboudi/Rvwabbit/blob/master/src/write_vw2.cpp
Maybe we could reuse some of that code

**Comment by eddelbuettel** [comment]
Absolutely want to use that Rcpp version ... but (and it has been a few months since I looked at it) I think it choked over the regression example we have in rvw.  

We'll get there.  And more easily with four eyes than with two.
